### ISSUE TITLE
2 Setup Infrastracture Story

### ISSUE THREAD

**Issue by compscied** [dps2018-dcs801/t2-bank#5]
As an infrastructure engineer I want to set up an infrastructure for the web server, log ingestion and visualization framework.

**Comment by JonasEMalmsten** [comment]
Added logstash user to adm group for read access to apache logs. logstash is now working, running as a service and copying data from /var/log/apache2/access.log into elasticsearch. When using kibana, select index "logstash-2015.11.10".
